# Generated by Django 4.2.11 on 2026-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticreport',
            name='report_id',
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='user_report_number',
            field=models.IntegerField(default=0),
        ),
    ]
