# Generated by Django 4.2.11 on 2026-04-28 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=50, null=True)),
                ('nutrition_advice', models.TextField()),
                ('activity_advice', models.TextField()),
                ('sleep_advice', models.TextField()),
                ('mental_health_advice', models.TextField()),
                ('safety_alerts', models.TextField(blank=True, null=True)),
                ('reasoning', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_recommendations_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light (exercise 1-3 days/week)'), ('moderate', 'Moderate (exercise 3-5 days/week)'), ('active', 'Active (exercise 6-7 days/week)'), ('very_active', 'Very Active (hard exercise & physical job)')], default='sedentary', max_length=20)),
                ('health_conditions', models.TextField(blank=True, help_text='List conditions, e.g., Diabetes, Hypertension', null=True)),
                ('allergies', models.TextField(blank=True, help_text='List any allergies', null=True)),
                ('dietary_preference', models.CharField(choices=[('no_preference', 'No Preference'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('keto', 'Keto'), ('paleo', 'Paleo')], default='no_preference', max_length=20)),
                ('smoking_status', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], default='never', max_length=20)),
                ('hours_of_sleep', models.PositiveIntegerField(blank=True, help_text='Average hours of sleep per night', null=True)),
                ('breakfast', models.TextField(blank=True, help_text='Typical breakfast details', null=True)),
                ('lunch', models.TextField(blank=True, help_text='Typical lunch details', null=True)),
                ('dinner', models.TextField(blank=True, help_text='Typical dinner details', null=True)),
                ('other_routine', models.TextField(blank=True, help_text='Any other important daily routines', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
